nao_back_office_observations:
    path:     /mes-observations
    defaults: { _controller: NAOBackOfficeBundle:BackOffice:observations }

nao_back_office_add:
    path:   /ajouter
    defaults: { _controller: NAOBackOfficeBundle:BackOffice:add }

nao_back_office_validations:
    path:   /validations
    defaults: { _controller: NAOBackOfficeBundle:BackOffice:validations }

nao_back_office_account:
    path:   /mon-compte
    defaults: { _controller: NAOBackOfficeBundle:BackOffice:account }

nao_back_office_admin:
    path:   /admin
    defaults: { _controller: NAOBackOfficeBundle:BackOffice:admin }
