nao_back_office:
    resource: "@NAOBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

nao_app:
    resource: "@NAOAppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
