# app/config/security.yml

security:
    # Encode les mots de passe
    encoders:
        NAO\AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_NATUR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_NATUR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_NATUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: NAOAppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|uploads|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login
                default_target_path: nao_back_office_observations
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/backoffice/, roles: ['ROLE_ADMIN', 'ROLE_USER', 'ROLE_NATUR'] }
